### ISSUE TITLE
Exception: Reader closed when using AsEnumerable 

### ISSUE THREAD

**Issue by aamirMasood** [jhgbrt/Net.Code#5]
When using AsEnumerable with stored procedure returning a single row, Count method closes the reader and further traversing is not possible. 
`var rows = db.StoredProcedure("SP_AuthenticateUser").WithParameters(new { Username = user.Username, TenantId = user.TenantId }).AsEnumerable();`
`if(rows.Count() == 1){`
`var row = rows.First();// Exception due to reader being closed.`
`}`

**Comment by jhgbrt** [comment]
At the moment, this is by design; AsEnumerable wraps the underlying datareader. But I agree this may not be the expected behaviour. Anyway, closing this issue here b/c I am maintaining it now in a different repository (yadal). Feel free to re-open it there.
